spring.application.name=app-eve-ms-users
# Cargar credenciales (no versionado)
spring.config.import=classpath:config/private.properties

# DataSource
spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}

# Swagger
springdoc.api-docs.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true